export const USER_LOGIN_SUCCESS = 'auth/USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'auth/USER_LOGIN_FAILURE';

export const USER_REGISTER_SUCCESS = 'auth/USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'auth/USER_REGISTER_FAILURE';

export const JSON_API_SUCCESS = 'api/JSON_API_SUCCESS';
export const JSON_API_FAILURE = 'api/JSON_API_FAILURE';
export const JSON_API_REQUEST = 'api/JSON_API_REQUEST';
